Feature/custom message for non custom penalties
kit-sdq/programming-lecture-eclipse-artemis pull request #139
Opened 2021-12-10 23:08 UTC by Shirkanesi

As already said in #83 I started to work on the feature to create penalties defined by the JSON but also add an additional custom message to them.
Currently I decided shift-clicking and middle-clicking the penalty-button is a good way to open this message-dialog. However, this can be changed or extended to other triggers.

The annotations are created by simply appending the customMessage to the message of the mistake (Separated by `<br/>Explaination:`). (Of course only iff there is a customMessage present)
The JSON-format was not modified, because the mistake and the customMessage can be stored simultaniously by the old system.

ToDo:
- [ ] Cleanup code and imports
- [ ] Test compatibility with old versions of the plugin (to make sure nothing breaks)
- [ ] Test the code on multiple systems (I don't known what could break, but I'll do it anyway)
  - [ ] Windows 11
  - [ ] Windows 10
  - [ ] Linux Mint

Screenshots:
![grafik](https://user-images.githubusercontent.com/30196411/145652193-ff2f0d5f-e995-40e6-8c8f-0cf592ff996c.png)
![grafik](https://user-images.githubusercontent.com/30196411/145652250-f458c7d4-3d4a-4648-a6fe-9c2d7dc11072.png)

2021-12-10 23:11 UTC, I-Al-Istannen commented on bundles/edu.kit.kastel.sdq.eclipse.grading.core/src/edu/kit/kastel/sdq/eclipse/grading/core/artemis/AnnotationMapper.java
> +				detailText += "<br />Explaination: " + annotation.getCustomMessage().get();
```suggestion
				detailText += "<br />Explanation: " + annotation.getCustomMessage().get();

```

2021-12-19 11:34 UTC, Shirkanesi commented
Behaviour of old versions of the plugin tested. Everything working perfectly; nothing seems to break (hence the JSON did not change at all).
Re-Submitting feedback with an old version will only not create the custom message again.

2021-12-20 13:41 UTC, dfuchss requested changes
Nice work! One small detail .. see comment :)

2021-12-20 13:42 UTC, dfuchss commented
> Behaviour of old versions of the plugin tested. Everything working perfectly; nothing seems to break (hence the JSON did not change at all). Re-Submitting feedback with an old version will only not create the custom message again.

Re-Submitting with the newer version should work, am I right?
I'll test it later, but I thought I should ask this question before.

2021-12-20 14:00 UTC, Shirkanesi commented
> > Behaviour of old versions of the plugin tested. Everything working perfectly; nothing seems to break (hence the JSON did not change at all). Re-Submitting feedback with an old version will only not create the custom message again.
> 
> Re-Submitting with the newer version should work, am I right? I'll test it later, but I thought I should ask this question before.

I actually never tested this. Good point. 
In theory it should work without any problem because the "customMessage" is empty and therefore should cause no problem. However good idea to test this case :)

2021-12-21 08:45 UTC, dfuchss approved these changes
It works :)

2021-12-21 08:46 UTC, merged