`General/Bugfix` First ideas on how to fix null-Feedbacks
kit-sdq/programming-lecture-eclipse-artemis pull request #152
Opened 2021-12-15 22:21 UTC by Shirkanesi

As described in #151 weird things go on where the feedbacks will contain null-values which introduce some weird bugs in the plugin.
I'm currently trying to find all the issues that (might) break by null-Feedbacks, however it's not realy clear where exactly everything breaks. 
To increase chances of success, I also added proper logging to `ViewAlertObserver` in order to get more information about the real error happening somewhere.

I'm realy interested in your oppinions whether we should directly add this logging to production or we should first investigate more before.

2021-12-15 22:22 UTC, Shirkanesi commented
Draft for now, however your oppinion is required @dfuchss

2021-12-16 09:43 UTC, dfuchss commented
looks good to me.

2021-12-16 20:12 UTC, Shirkanesi commented
I tested around even more. I've managed to reproduce the bug at a relatively consistant rate.
It seems like the issue with `A is null` happens everytime an eclipse-instance uploads new assessments. However sometimes those uploads will fail with `400 Bad Request`. In this case the data seems to be not updated yet but parts of the feedbacks in the database are broken.

This 400 seems to be triggered by a (too) big request of some kind. However I'm not exactly sure what exactly breaks here BUT it is pretty sure an issue in the grading-plugin.

A temporary fix for this issue is clearing the current feedback and rewriting everything. This clearing can be done by an Instructor OR by aborting the assessment (if the button is still working...).

2021-12-17 10:51 UTC, Shirkanesi commented
Finally found the issue; `createNewManualUnreferencedFeedback` created to large Feedbacks...
Now fixed by creating multiple annotations.

2021-12-17 12:22 UTC, dfuchss requested changes
Looks good to me. See remarks :)

2021-12-17 12:22 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/observers/ViewAlertObserver.java
> +	private static final ILog log = Platform.getLog(ViewAlertObserver.class);
Logging is good!

2021-12-17 12:22 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.grading.core/src/edu/kit/kastel/sdq/eclipse/grading/core/artemis/AnnotationMapper.java
> +		if (lines.size() == 0) {
isEmpty :) ?
```suggestion
		if (lines.isEmpty()) {

```

2021-12-17 12:22 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.grading.core/src/edu/kit/kastel/sdq/eclipse/grading/core/artemis/AnnotationMapper.java
> +			if (text.length() + lines.get(i).length() >= FEEDBACK_DETAIL_TEXT_MAX_CHARACTERS - annotationHeadline.length() - 50) {
Why `50`?

2021-12-17 12:46 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.grading.core/src/edu/kit/kastel/sdq/eclipse/grading/core/artemis/AnnotationMapper.java
> +			if (text.length() + lines.get(i).length() >= FEEDBACK_DETAIL_TEXT_MAX_CHARACTERS - annotationHeadline.length() - 50) {
Yes you are right :) .. Maybe add it to a constant as well :)

2021-12-17 13:28 UTC, dfuchss commented
Works as described. Thanks :)

2021-12-17 13:29 UTC, merged