[DRAFT] `Feature`: Translations
kit-sdq/programming-lecture-eclipse-artemis pull request #189
Opened 2022-04-14 11:07 UTC by Shirkanesi

I've started to add translations to the tool, however not done yet.

We might need to figure out if there is a better location for the ResourceBundle than the src-folder. 
Sadly I couldn't figure out whether there is a dedicated resource-folder somewhere when dealing with eclipse-plugins :(

2022-04-15 10:26 UTC, Shirkanesi commented
In order to not overcomplicate the feature a restart of eclipse is required to update the language.
Otherwise we would need to separate the creation of every button/label/... from the code their behaviour and layout is defined. This would be an ugly solution (in my opinion)

2022-04-19 19:21 UTC, dfuchss commented
I would suggest to load the actual strings into one ore more static classes that hold constants for the current language (could be some lazily loaded constants). These constants can be used in the classes instead of using the keys in the UI code directly. I think that might be easier, since you deal with the language in dedicated locations :) But that's discussable.

2022-05-01 22:28 UTC, Shirkanesi commented
I've put this feature on pause until we figure out a good way of handling the configurations for both editions. (https://github.com/kit-sdq/programming-lecture-eclipse-artemis/issues/196)

2022-05-12 06:04 UTC, Shirkanesi commented
> I would suggest to load the actual strings into one ore more static classes that hold constants for the current language (could be some lazily loaded constants). These constants can be used in the classes instead of using the keys in the UI code directly. I think that might be easier, since you deal with the language in dedicated locations :) But that's discussable.

I don't realy like to use constants for this. But I can imagine using an enum for this:
```java
public enum Messages {
	
	TAB_GRADING("tabs.grading"),
	TAB_ASSESSMENT_COURSE("tabs.assessment.course"),
	TAB_ASSESSMENT_EXAM("tabs.assessment.exam"),
	
	SETTINGS_DESCRIPTION("settings.description"),
	SETTINGS_URL("settings.url"),
	SETTINGS_USERNAME("settings.username"),
	SETTINGS_PASSWORD("settings.password")
	;
	
	private final String resourceBundleKey;
	
	Messages(String resourceBundleKey) {
		this.resourceBundleKey = resourceBundleKey;
	}
	
	public String getString() {
		return ResourceBundleProvider.getResourceBundle().getString(this.resourceBundleKey);
	}
	
	public String format(Object... params) {
		return String.format(this.getString(), params);
	}

}
```

2022-05-12 06:17 UTC, dfuchss commented
I would suggest something like this (without resource files)

Define an interface I18N or L18N (as these abbr. are well known).
These interfaces can contain methods for each string we might want to use. (might be long but will be more readable in the code)

e.g., `L18N.settingsConfigPath()` instead of `ResourceBundleProvider.getResourceBundle().getString("settings.grading.absoluteConfigPath")`

All of these methods should be default methods like:

```java
if(LANGUAGE_OVERRIDE.isPresent()) // Static attribute that can be set if we do not want to use English
    return LANGUAGE_OVERRIDE.methodName()
return "My English Text for Default";
```

Furthermore, we would need some setter for the Language Override.


This kind of impl would have the following benefits:

* No need for a bunch of string variables as keys :D 
* Default Methods would ensure that a new field defaults to english if not translated (overridden in e.g., `GermanLang implements L18N`
* Method calls would be much shorter and therefore more readable.

The interface could look like this:

```java

interface L18N {
    static Container<L18N> LANGUAGE_OVERRIDE = Container.of(CommonActivator.getCurrentLanguage());

   deafault String settingAbsolutePath(){ // Maybe also use "?" then the one liner might be good readable.
       if(!LANGUAGE_OVERRIDE.isPresent() || isThisDefaultMethod()) // This has to be figured out (I'm not sure here). We have to make sure that we do not get an endless loop here (if override is present & method not overridden)
            return "Config Path Settings:"
       return LANGUAGE_OVERRIDE.get().settingAbsolutePath(); 
    }

}
```



What is your opinion on that ?

2022-05-12 06:19 UTC, Shirkanesi commented
lgtm. I'll work on it

2022-05-12 06:21 UTC, dfuchss commented
Thanks. The difficult part will be the default handling (as commented) I'm looking forward for the impl of that :)

2022-05-12 07:34 UTC, Shirkanesi commented
I think those entire if-statements can be replaced by simple polymorphism. Just define the return of the default value in the interface and create a class for every override. 
Then the correct value will be returned due to dynamic binding.
(Given the I18N-object is swapped based on the selected language)

2022-05-12 07:46 UTC, dfuchss commented
Yes, you are right. The only remaining part would be the swapping of the object. And the shortcut to it should be not that long :)

2022-05-12 07:46 UTC, dfuchss commented
I've overseen that this morning because in my mind the methods were also static :D

2022-05-12 07:48 UTC, Shirkanesi commented
I actually would just create a class like this:
```java
public class LanguageOverrideContainer {

	private static I18N currentOverride = new DefaultLanguage(); // todo swap
	
	public static I18N LANGUAGE_OVERRIDE() {
		return currentOverride;
	}
	
}
```

and just `import static ...LANGUAGE_OVERRIDE` everywhere we need it.

2022-05-12 08:02 UTC, dfuchss commented
You would still have to call LANGUAGE_OVERRIDE() because it's a method

2022-05-12 08:10 UTC, Shirkanesi commented
> You would still have to call LANGUAGE_OVERRIDE() because it's a method

Yes. But `LANGUAGE_OVERRIDE().settingsLanguage()` is quite readable and prevents anoying `.get()` calls :D

2022-05-12 08:17 UTC, dfuchss commented
Yes. Maybe simply call the Method L18N or I18N  :)

2022-05-12 08:18 UTC, dfuchss commented
And the container simply LanguageSettings

2022-05-12 11:20 UTC, dfuchss requested changes

2022-05-12 11:20 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/preferences/ArtemisPreferencesPage.java
> +		var artemisPassword = new StringFieldEditor(I18N().settingsPassword(), I18N().settingsPassword(), parent);
PrefConstants should not be part of I18N :)

2022-05-13 06:45 UTC, dfuchss requested changes
First look on the translations :)

2022-05-13 06:45 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/languages/GermanLanguage.java
> +		return "Benutze mehrzeile Textbox für benutzerdefinierte Abzüge";
```suggestion
		return "Benutze mehrzeilige Textbox für benutzerdefinierte Abzüge";
```

2022-05-13 06:45 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/languages/GermanLanguage.java
> +		return "Einstellungen für Artemis Grading";
```suggestion
		return "Einstellungen für Artemis";
```

2022-05-13 06:45 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/languages/GermanLanguage.java
> +		return "Erweiterte Einstellungen für Artemis Grading";
```suggestion
		return "Erweiterte Einstellungen für Artemis";
```

2022-05-13 06:45 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/languages/I18N.java
> +		return "Set preferences for Artemis Grading";
```suggestion
		return "Set preferences for Artemis";
```

2022-05-13 06:45 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/languages/I18N.java
> +		return "Set advanced settings for Artemis Grading";
```suggestion
		return "Set advanced settings for Artemis";
```

2022-05-13 11:29 UTC, dfuchss requested changes

2022-05-13 11:29 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/preferences/PreferenceInitializer.java
> +		store.setDefault(PreferenceConstants.GENERAL_PREFERRED_LANGUAGE, "English");
I would suggest to get this from the LanguageSettings.

2022-05-13 15:19 UTC, dfuchss approved these changes
Lgtm

2022-05-13 15:20 UTC, merged