Add an option to open files automatically & expand all packages when starting an assessment
kit-sdq/programming-lecture-eclipse-artemis pull request #263
Opened 2022-11-21 23:03 UTC by Feuermagier

### Checklist
- [x] I tested *all* changes and their related features locally or with a test instance of Artemis.
- [x] I documented the Java code using JavaDoc style.
- [ ] I documented the changes in the Documentation (/docs).

### Motivation and Context
When starting a new assessment, one (or at least I) typically start with expanding all packages in the package explorer and finding and opening the main class. With this change, all packages get expanded automatically after starting an assessment. In addition, I've added a new option to the advanced Artemis preferences to configure whether to open no class, the main class, or all types after starting an assessment.

### Description
I've had to add dependencies to a number of Eclipse packages, namely JDT packages (to find the main class) and navigator packages (to access the package explorer). By default, only the main class will be opened when starting a new assessment. If there are multiple main classes, only one is opened. While the opening of files is configurable, I don't think anyone doesn't want to have all packages expanded automatically, so I haven't added an option to disable this.

### Steps for Testing
Just start a new assessment. If it works, the main class should be opened automatically (as long as there is one) and all packages (including the default package) should be expanded.

2022-11-21 23:10 UTC, Feuermagier commented
Btw, how can I run spotless locally? Running mvn spotless:check or spotless:apply in the root directory of the repository yields no format violations.

2022-11-21 23:27 UTC, dfuchss commented
`mvn spotless:apply` should work

2022-11-21 23:28 UTC, dfuchss commented
I'll have a look at this PR asap :)

2022-11-21 23:35 UTC, dfuchss commented
> Btw, how can I run spotless locally? Running mvn spotless:check or spotless:apply in the root directory of the repository yields no format violations.

Strange bug. I'll have a look into that

2022-11-22 12:16 UTC, dfuchss commented
I guess the problem is that spotless defines "<ratchetFrom>origin/main</ratchetFrom>" .. and you are not working on a feature branch :)

2022-11-22 18:42 UTC, dfuchss commented
Thx a lot :)
I'll look at it today or tomorrow

2022-11-23 18:23 UTC, dfuchss commented
@Feuermagier I like that feature. I'd suggest to slightly modify the Expand All option: If a main method exist, in the end the open tab should be the class containing the main method. Does that make sense ?

2022-11-23 18:36 UTC, dfuchss requested changes
Only one minor change regarding the code

2022-11-23 18:36 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/utilities/AssessmentUtilities.java
> +				Platform.getLog(AssessmentUtilities.class).error("Failed to open the java code element", e);
Please add the log as constant called `log` to the class

2022-11-23 18:36 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.common.view/src/edu/kit/kastel/eclipse/common/view/utilities/AssessmentUtilities.java
> +		return (ProjectExplorer) page.findView("org.eclipse.ui.navigator.ProjectExplorer");
What does happen if it is not open :)

2022-11-23 18:36 UTC, dfuchss commented on bundles/edu.kit.kastel.sdq.eclipse.grading.view/src/edu/kit/kastel/eclipse/grading/view/assessment/ArtemisGradingView.java
> +			Platform.getLog(ArtemisGradingView.this.getClass()).error("JDT failure", e);
Same here :)

2022-11-23 23:16 UTC, Feuermagier commented
> @Feuermagier I like that feature. I'd suggest to slightly modify the Expand All option: If a main method exist, in the end the open tab should be the class containing the main method. Does that make sense ?

Yeah, it should do so now. I've also made it so that only the main class is highlighted in the project explorer when opening all types.

2022-11-24 08:41 UTC, dfuchss commented
One last point :)
Could you update the images of the settings in the documentation that they include the new options ?

2022-11-25 00:22 UTC, Feuermagier commented
Done :)

2022-11-25 08:12 UTC, dfuchss approved these changes

2022-11-25 08:12 UTC, merged